language: go

go:
  - 1.7.x
  - 1.8.x
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -u github.com/go-ego/cedar
  - go get -u -v -t ./...

# notifications:
#   email:
#     - .com